export const info = {
  key: 1,
  title: "Blood Glucose Values",
  color: "#8884d8",
  fill: true,
  dataKey: "bg_value",
  data: [
    { timestamp: "00:00", bg_value: 100 },
    { timestamp: "05:00", bg_value: 110 },
    { timestamp: "10:00", bg_value: 120 },
    { timestamp: "15:00", bg_value: 115 },
    { timestamp: "20:00", bg_value: 105 },
    { timestamp: "00:00", bg_value: 70 },
    { timestamp: "05:00", bg_value: 110 },
    { timestamp: "10:00", bg_value: 157 },
    { timestamp: "15:00", bg_value: 161 },
    { timestamp: "20:00", bg_value: 124 },
  ],
  pointBorderColor: "aqua",
  borderColor: "black",
  backGroundColor: "aqua",
};

export const daymeans = {
  key: 2,
  title: "Daily Value Means",
  color: "#FF8042",
  dataKey: "mean",
  data: [
    {
      day: "Sun",
      mean: 60,
    },
    {
      day: "Mon",
      mean: 75,
    },
    {
      day: "Tue",
      mean: 62,
    },
    {
      day: "Wed",
      mean: 78,
    },
    {
      day: "Thu",
      mean: 83,
    },
    {
      day: "Fri",
      mean: 96,
    },
    {
      day: "Sat",
      mean: 102,
    },
  ],
};

export const rows = [
  {
    id: 1,
    day: "Sunday",
    min: 87,
    max: 159,
    stdDev: 10,
    mean: 124,
    status: "Normal",
  },
  {
    id: 2,
    day: "Monday",
    min: 81,
    max: 140,
    stdDev: 10,
    mean: 131,
    status: "Normal",
  },
  {
    id: 3,
    day: "Tuesday",
    min: 84,
    max: 148,
    stdDev: 10,
    mean: 134,
    status: "Normal",
  },
  {
    id: 4,
    day: "Wednesday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 144,
    status: "Normal",
  },
  {
    id: 5,
    day: "Thursday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 6,
    day: "Thursday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 144,
    status: "Normal",
  },
  {
    id: 7,
    day: "Friday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 8,
    day: "Saturday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 144,
    status: "Normal",
  },
  {
    id: 9,
    day: "Sunday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 10,
    day: "Monday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 144,
    status: "Normal",
  },
  {
    id: 11,
    day: "Tuesday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 9,
    day: "Wednesday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 144,
    status: "Normal",
  },
  {
    id: 10,
    day: "Thursday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 11,
    day: "Friday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
  {
    id: 12,
    day: "Saturday",
    min: 90,
    max: 150,
    stdDev: 10,
    mean: 130,
    status: "Normal",
  },
];
